In [1]:
from pathlib import Path

data_dir = Path("../data")

for file in data_dir.rglob("*"):
    if file.is_file():
        print(file)

../data/pers_20.csv
../data/veh_17.csv
../data/veh_16.csv
../data/acc_18.csv
../data/acc_19.csv
../data/acc_20.csv
../data/pers_19.csv
../data/pers_18.csv
../data/pers_16.csv
../data/veh_20.csv
../data/pers_17.csv
../data/veh_18.csv
../data/veh_19.csv
../data/acc_17.csv
../data/acc_16.csv
../data/.complete/datasets/jonbown/us-2020-traffic-accidents/3/bundle.complete

In [3]:
import pandas as pd

df = pd.read_csv("../data/acc_20.csv")

df.head()

,CASENUM,STRATUM,STRATUMNAME,REGION,REGIONNAME,PSU,PJ,PSU_VAR,URBANICITY,URBANICITYNAME,...,WEATHR_IM,WEATHR_IMNAME,MAXSEV_IM,MAXSEV_IMNAME,NO_INJ_IM,NO_INJ_IMNAME,ALCHL_IM,ALCHL_IMNAME,PSUSTRAT,WEIGHT
0,202002121240,9,Stratum 9 - LMY PV No Injuries in Crash,4,"West (MT, ID, WA, OR, CA, NV, NM, AZ, UT, CO, ...",20,4140,20,2,Rural Area,...,10,Cloudy,0,No Apparent Injury (O),0,No Person Injured/Property Damage Only Crash,2,No Alcohol Involved,25,161.358280
1,202002121829,8,Stratum 8 - NLMY PV Minor Injury,3,"South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...",28,4139,28,1,Urban Area,...,1,Clear,2,Suspected Minor Injury (B),1,1,2,No Alcohol Involved,11,131.962215
2,202002121849,9,Stratum 9 - LMY PV No Injuries in Crash,3,"South (MD, DE, DC, WV, VA, KY, TN, NC, SC, GA,...",12,4142,12,1,Urban Area,...,1,Clear,0,No Apparent Injury (O),0,No Person Injured/Property Damage Only Crash,2,No Alcohol Involved,12,165.957768
3,202002123484,10,Stratum 10 - Other,4,"West (MT, ID, WA, OR, CA, NV, NM, AZ, UT, CO, ...",20,4140,20,2,Rural Area,...,4,Snow,0,No Apparent Injury (O),0,No Person Injured/Property Damage Only Crash,2,No Alcohol Involved,25,214.206572
4,202002123576,10,Stratum 10 - Other,1,"Northeast (PA, NJ, NY, NH, VT, RI, MA, ME, CT)",22,4149,22,2,Rural Area,...,4,Snow,0,No Apparent Injury (O),0,No Person Injured/Property Damage Only Crash,2,No Alcohol Involved,5,220.296289

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54745 entries, 0 to 54744
Data columns (total 80 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CASENUM         54745 non-null  int64
 1   STRATUM         54745 non-null  int64
 2   STRATUMNAME     54745 non-null  object
 3   REGION          54745 non-null  int64
 4   REGIONNAME      54745 non-null  object
 5   PSU             54745 non-null  int64
 6   PJ              54745 non-null  int64
 7   PSU_VAR         54745 non-null  int64
 8   URBANICITY      54745 non-null  int64
 9   URBANICITYNAME  54745 non-null  object
 10  VE_TOTAL        54745 non-null  int64
 11  VE_FORMS        54745 non-null  int64
 12  PVH_INVL        54745 non-null  int64
 13  PEDS            54745 non-null  int64
 14  PERMVIT         54745 non-null  int64
 15  PERNOTMVIT      54745 non-null  int64
 16  NUM_INJ         54745 non-null  int64
 17  NUM_INJNAME     54745 non-null  object
 18  MONTH           54745 non-null  int64
 19  MONTHNAME       54745 non-null  object
 20  YEAR            54745 non-null  int64
 21  YEARNAME        54745 non-null  int64
 22  DAY_WEEK        54745 non-null  int64
 23  DAY_WEEKNAME    54745 non-null  object
 24  HOUR            54745 non-null  int64
 25  HOURNAME        54745 non-null  object
 26  MINUTE          54745 non-null  int64
 27  MINUTENAME      54745 non-null  object
 28  HARM_EV         54745 non-null  int64
 29  HARM_EVNAME     54745 non-null  object
 30  ALCOHOL         54745 non-null  int64
 31  ALCOHOLNAME     54745 non-null  object
 32  MAX_SEV         54745 non-null  int64
 33  MAX_SEVNAME     54745 non-null  object
 34  MAN_COLL        54745 non-null  int64
 35  MAN_COLLNAME    54745 non-null  object
 36  RELJCT1         54745 non-null  int64
 37  RELJCT1NAME     54745 non-null  object
 38  RELJCT2         54745 non-null  int64
 39  RELJCT2NAME     54745 non-null  object
 40  TYP_INT         54745 non-null  int64
 41  TYP_INTNAME     54745 non-null  object
 42  WRK_ZONE        54745 non-null  int64
 43  WRK_ZONENAME    995 non-null    object
 44  REL_ROAD        54745 non-null  int64
 45  REL_ROADNAME    54745 non-null  object
 46  LGT_COND        54745 non-null  int64
 47  LGT_CONDNAME    54745 non-null  object
 48  SCH_BUS         54745 non-null  int64
 49  SCH_BUSNAME     54745 non-null  object
 50  INT_HWY         54745 non-null  int64
 51  INT_HWYNAME     54745 non-null  object
 52  WEATHER         54745 non-null  int64
 53  WEATHERNAME     54745 non-null  object
 54  WKDY_IM         54745 non-null  int64
 55  WKDY_IMNAME     54745 non-null  object
 56  HOUR_IM         54745 non-null  int64
 57  HOUR_IMNAME     54745 non-null  object
 58  MINUTE_IM       54745 non-null  int64
 59  MINUTE_IMNAME   54745 non-null  int64
 60  EVENT1_IM       54745 non-null  int64
 61  EVENT1_IMNAME   54745 non-null  object
 62  MANCOL_IM       54745 non-null  int64
 63  MANCOL_IMNAME   54745 non-null  object
 64  RELJCT1_IM      54745 non-null  int64
 65  RELJCT1_IMNAME  54745 non-null  object
 66  RELJCT2_IM      54745 non-null  int64
 67  RELJCT2_IMNAME  54745 non-null  object
 68  LGTCON_IM       54745 non-null  int64
 69  LGTCON_IMNAME   54745 non-null  object
 70  WEATHR_IM       54745 non-null  int64
 71  WEATHR_IMNAME   54745 non-null  object
 72  MAXSEV_IM       54745 non-null  int64
 73  MAXSEV_IMNAME   54745 non-null  object
 74  NO_INJ_IM       54745 non-null  int64
 75  NO_INJ_IMNAME   54745 non-null  object
 76  ALCHL_IM        54745 non-null  int64
 77  ALCHL_IMNAME    54745 non-null  object
 78  PSUSTRAT        54745 non-null  int64
 79  WEIGHT          54745 non-null  float64
dtypes: float64(1), int64(47), object(32)
memory usage: 33.4+ MB

In [5]:
df.describe()

,CASENUM,STRATUM,REGION,PSU,PJ,PSU_VAR,URBANICITY,VE_TOTAL,VE_FORMS,PVH_INVL,...,MANCOL_IM,RELJCT1_IM,RELJCT2_IM,LGTCON_IM,WEATHR_IM,MAXSEV_IM,NO_INJ_IM,ALCHL_IM,PSUSTRAT,WEIGHT
count,5.474500e+04,54745.000000,54745.000000,54745.000000,54745.000000,54745.000000,54745.000000,54745.000000,54745.000000,54745.000000,...,54745.000000,54745.000000,54745.000000,54745.000000,54745.000000,54745.000000,54745.000000,54745.000000,54745.000000,54745.000000
mean,2.020026e+11,7.050726,2.738150,48.196803,2325.352087,52.351210,1.252498,1.789734,1.730167,0.059567,...,2.587414,0.066508,2.824970,1.647493,2.410266,1.066380,0.815161,1.922751,12.628021,95.914463
std,2.151866e+05,2.596944,0.879934,19.900415,1666.926528,32.705451,0.434449,0.655057,0.641039,0.296503,...,2.920490,0.249171,3.541586,1.062263,3.091939,1.180133,0.979352,0.266989,6.204774,66.419435
min,2.020021e+11,2.000000,1.000000,10.000000,45.000000,10.000000,1.000000,1.000000,1.000000,0.000000,...,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,8.230572
25%,2.020025e+11,5.000000,2.000000,32.000000,573.000000,32.000000,1.000000,1.000000,1.000000,0.000000,...,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,2.000000,9.000000,32.376107
50%,2.020026e+11,8.000000,3.000000,48.000000,1800.000000,48.000000,1.000000,2.000000,2.000000,0.000000,...,1.000000,0.000000,2.000000,1.000000,1.000000,1.000000,1.000000,2.000000,13.000000,95.296227
75%,2.020028e+11,9.000000,3.000000,65.000000,4142.000000,67.000000,2.000000,2.000000,2.000000,0.000000,...,6.000000,0.000000,3.000000,2.000000,2.000000,2.000000,1.000000,2.000000,16.000000,162.829310
max,2.020030e+11,10.000000,4.000000,83.000000,4153.000000,214.000000,2.000000,15.000000,15.000000,6.000000,...,11.000000,1.000000,20.000000,7.000000,12.000000,8.000000,14.000000,2.000000,25.000000,483.948635